

export type Language = 'en' | 'zh';

export const translations = {
  en: {
    sidebar: {
      notebooks: "Notebooks",
      notebook: "Notebook",
      note: "Note",
      today: "Today's Filter",
      todayStickies: "Today's Stickies",
      bookshelf: "Bookshelf",
      settings: "Settings",
      help: "User Manual"
    },
    groups: {
      title: "Your Notebooks",
      newGroup: "New Notebook",
      deleteConfirmTitle: "Delete Notebook",
      deleteConfirmMsg: "Are you sure you want to delete this notebook and ALL its events? This cannot be undone."
    },
    toolbar: {
      sortingActive: "Sorting active",
      dragToReorder: "Drag to reorder",
      doubleClick: "Double-click to edit",
      newEvent: "New Event",
      pinAll: "Pin View",
      unpinAll: "Unpin All",
      pinAllTitle: "Pin all events in current view",
      unpinAllTitle: "Unpin all events in current view",
      dataOptions: "Data Options",
      themeSettings: "Theme Settings",
      language: "Language",
      help: "User Manual",
      filter: "Filter"
    },
    settingsModal: {
      title: "Settings",
      general: "General",
      bookshelf: "Bookshelf",
      notebook: "Notebook(s)",
      presets: "Notes",
      ai: "AI / LLM",
      language: "Language",
      bgType: "Background Type",
      bgColor: "Color",
      bgImage: "Image",
      opacity: "Opacity",
      texture: "Paper Texture",
      newPreset: "Save New Preset",
      deletePreset: "Delete",
      manageBooks: "Manage Books",
      addBook: "Add Book",
      bookTitle: "Title",
      bookUrl: "URL",
      interactiveMode: "Interactive Bookshelf",
      interactiveModeDesc: "Click books to visit websites. Hover for effects.",
      bg3d: "Interactive",
      bgSolid: "Solid Color",
      bgImg: "Custom Image",
      generatedBy: "This project was generated by Gemini 3 Pro Preview and completed with Vibe Coding.",
      llmProvider: "LLM Provider",
      apiKey: "API Key",
      modelName: "Model Name",
      customPrompt: "Custom System Prompt",
      save: "Save Config",
      autoSave: "Auto-Save Interval (XLSX)",
      autoSaveDesc: "Download XLSX backup automatically.",
      minutes: "min",
      off: "Off"
    },
    dataMenu: {
      openFolder: "Set Data Folder",
      exportCSV: "Export CSV (Current)",
      importCSV: "Import CSV (Current)",
      exportXLSX: "Export All (XLSX)",
      importXLSX: "Import All (XLSX)",
      exportRecords: "Export Weekly Records",
      downloadPython: "Download Desktop App (.py)"
    },
    themeMenu: {
      desktopTheme: "Bookshelf Theme",
      notebookTheme: "Notebook Theme",
      reset: "Reset",
      resetDesktopMsg: "Restore bookshelf background to default settings?",
      resetNotebookMsg: "Restore notebook appearance to default settings?",
      paperTexture: "Paper Texture"
    },
    table: {
      content: "Content",
      added: "Added",
      start: "Start",
      end: "End",
      location: "Location",
      importance: "Imp.",
      status: "Status",
      reminder: "Reminder",
      actions: "Actions",
      empty: "No events found.",
      startAction: "Start",
      finishAction: "Finish",
      reopenAction: "Reopen",
      partialAction: "Partial"
    },
    filter: {
      title: "Filter Events",
      reset: "Reset Filters",
      dateField: "Date Field",
      dateRange: "Date Range",
      from: "From",
      to: "To"
    },
    note: {
      placeholder: "Write something...",
      settings: "Note Style",
      decoration: "Decoration",
      position: "Position",
      paper: "Paper",
      presets: "Presets",
      applyPreset: "Apply",
      saveAsPreset: "Save as Preset",
      preview: "Preview",
      done: "Close",
      unpin: "Unpin",
      delete: "Delete",
      deleteConfirmTitle: "Delete Event",
      deleteConfirmMsg: "Are you sure you want to delete this event? This action cannot be undone."
    },
    styles: {
      clip: "Clip",
      pin: "Pin",
      tape: "Tape",
      spiral: "Spiral",
      washi: "Washi",
      minimal: "Minimal",
      torn: "Torn Paper",
      flower: "Flower",
      leaf: "Leaf"
    },
    textures: {
      solid: "Solid",
      lined: "Lined",
      grid: "Grid",
      dots: "Dots"
    },
    status: {
      todo: "To Do",
      inProgress: "In Progress",
      partial: "Partial",
      done: "Done"
    },
    importance: {
      high: "High",
      medium: "Med",
      low: "Low"
    },
    help: {
      title: "NoteMinder User Manual",
      sections: {
        general: {
          title: "General Overview",
          items: [
            "This project was generated by Gemini 3 Pro Preview and completed with Vibe Coding.",
            "Welcome to NoteMinder! This is a smart task management tool combining notebook organization with a flexible sticky-note desktop interface.",
            "Workspace: The application features a 'Bookshelf' background that can hold interactive links, and a sidebar for navigation.",
            "Data Structure: Tasks are organized into 'Notebooks'. You can have multiple notebooks for different contexts (Work, Personal, etc.).",
            "Stickies: Any task in a notebook can be 'pinned' to the desktop as a sticky note for better visibility."
          ]
        },
        bookshelf: {
          title: "Bookshelf (Desktop)",
          items: [
            "The Bookshelf is your main background. Click the 'Book' icon in the sidebar to hide windows and view the shelf.",
            "Interactive Books: Hover over books to see them pull out. Click to open their linked URL in a new tab.",
            "Editing: Double-click any book to edit its Title, URL, and Color. You can also drag books to different slots (coming soon).",
            "Adding Links: Click on empty grey slots to add a new book link.",
            "Configuration: You can also manage all book links in Settings -> Bookshelf."
          ]
        },
        notebooks: {
          title: "Notebook Management",
          items: [
            "Notebooks act as folders for your tasks.",
            "Create: Click the '+' button at the bottom of the list to add a new notebook.",
            "Rename: Double-click a notebook name to rename it.",
            "Delete: Hover over a notebook and click the 'X' icon. Note: This deletes all tasks inside it.",
            "Reorder: Drag and drop notebooks to change their order."
          ]
        },
        notebook: {
          title: "Task List (Notebook View)",
          items: [
             "This is the main spreadsheet-like view for managing tasks.",
             "Editing: Double-click any cell to edit content, time, status, etc. The layout adjusts automatically for smaller screens.",
             "AI Parsing: When adding a task, click the 'Sparkles' icon to let AI auto-detect time and location from your text.",
             "Filters: Click the 'Filter' button in the toolbar to filter by Date Range, Status, or Priority.",
             "Pinning: Click the Pin icon on a row to turn it into a sticky note. Use 'Pin View' (Layers icon) to pin all currently visible tasks.",
             "Unpin All: Click the 'Pin Off' icon to remove all sticky notes from the desktop at once.",
             "Quick Actions: Use the action buttons (Play, Partial, Check) in the rightmost column to quickly update status."
          ]
        },
        note: {
          title: "Sticky Notes",
          items: [
             "Sticky notes are desktop representations of your tasks.",
             "Moving: Drag notes anywhere on the screen.",
             "Resizing: Drag the bottom-right corner to resize.",
             "Styling: Click the 'Gear' icon on a note to change its color, texture, and decoration (tape, pin, clip).",
             "Presets: You can save your favorite styles as 'Presets' in Settings and apply them quickly.",
             "Status: The status icon (circle, play, pie chart, check) is shown on the note. You can update text directly on the note."
          ]
        },
        settings: {
          title: "Settings & AI",
          items: [
             "Theme: Customize the notebook opacity, background color, or set a custom image.",
             "AI / LLM: Configure the AI provider. Supports Gemini (default), OpenAI, and DeepSeek. You can provide your own API Key and custom System Prompts.",
             "Auto-Save: Configure automatic backup interval. The app will download an XLSX file periodically to save your data.",
             "Presets: Manage your sticky note style templates here."
          ]
        },
        update: {
          title: "Update History",
          items: [
            "v4.8.0: Added 'Partial' status, Advanced Filtering, Unpin All button, and responsive edit layouts.",
            "v4.6.0: Added Auto-Save configuration in Settings.",
            "v4.5.0: Added LLM configuration, Split Date/Time pickers, Notebook action buttons, and weekly export updates.",
            "v4.4.0: Added XLSX batch export, data folder settings.",
            "v4.3.0: Enhanced settings, interactive bookshelf, and UI improvements."
          ]
        }
      }
    }
  },
  zh: {
    sidebar: {
      notebooks: "笔记本库",
      notebook: "当前列表",
      note: "桌面便签",
      today: "今日待办",
      todayStickies: "今日便签",
      bookshelf: "书架桌面",
      settings: "系统设置",
      help: "使用说明"
    },
    groups: {
      title: "我的笔记本",
      newGroup: "新建笔记本",
      deleteConfirmTitle: "删除笔记本",
      deleteConfirmMsg: "确定要删除此笔记本及其所有事件吗？此操作无法撤销。"
    },
    toolbar: {
      sortingActive: "正在排序",
      dragToReorder: "拖拽调整顺序",
      doubleClick: "双击编辑",
      newEvent: "新建事件",
      pinAll: "一键固定",
      unpinAll: "一键取消",
      pinAllTitle: "将当前视图所有事件固定到桌面",
      unpinAllTitle: "取消当前视图所有事件的固定",
      dataOptions: "数据选项",
      themeSettings: "主题设置",
      language: "语言",
      help: "使用说明",
      filter: "筛选"
    },
    settingsModal: {
      title: "设置",
      general: "常规",
      bookshelf: "书架桌面",
      notebook: "笔记本(s)",
      presets: "便签样式",
      ai: "AI / 大模型",
      language: "语言",
      bgType: "背景类型",
      bgColor: "颜色",
      bgImage: "图片",
      opacity: "不透明度",
      texture: "纸张纹理",
      newPreset: "保存为新样式",
      deletePreset: "删除",
      manageBooks: "书籍管理",
      addBook: "添加书籍",
      bookTitle: "标题",
      bookUrl: "网址",
      interactiveMode: "书架交互模式已激活",
      interactiveModeDesc: "单击书本访问网页，悬停查看效果，双击编辑。",
      bg3d: "交互书架",
      bgSolid: "纯色背景",
      bgImg: "自定义图片",
      generatedBy: "本项目由 Gemini 3 Pro Preview 生成，并由 Vibe Coding 完成。",
      llmProvider: "模型提供商",
      apiKey: "API Key",
      modelName: "模型名称",
      customPrompt: "自定义提示词 (Prompt)",
      save: "保存配置",
      autoSave: "自动保存间隔 (XLSX)",
      autoSaveDesc: "定时自动下载 XLSX 备份文件。",
      minutes: "分钟",
      off: "关闭"
    },
    dataMenu: {
      openFolder: "设置数据保存文件夹",
      exportCSV: "导出 CSV (当前)",
      importCSV: "导入 CSV (当前)",
      exportXLSX: "批量导出 (XLSX)",
      importXLSX: "批量导入 (XLSX)",
      exportRecords: "导出周工时记录",
      downloadPython: "下载桌面版 (.py)"
    },
    themeMenu: {
      desktopTheme: "书架主题",
      notebookTheme: "笔记本主题",
      reset: "重置",
      resetDesktopMsg: "恢复书架背景为默认设置？",
      resetNotebookMsg: "恢复笔记本外观为默认设置？",
      paperTexture: "纸张纹理"
    },
    table: {
      content: "事件内容",
      added: "添加时间",
      start: "开始时间",
      end: "结束时间",
      location: "地点",
      importance: "优先级",
      status: "状态",
      reminder: "提醒",
      actions: "操作",
      empty: "未找到事件。",
      startAction: "开始",
      finishAction: "完成",
      reopenAction: "重开",
      partialAction: "部分完成"
    },
    filter: {
      title: "筛选事件",
      reset: "重置筛选",
      dateField: "时间类型",
      dateRange: "日期范围",
      from: "从",
      to: "至"
    },
    note: {
      placeholder: "写点什么...",
      settings: "样式设置",
      decoration: "装饰组件",
      position: "装饰位置",
      paper: "纸张风格",
      presets: "预设样式",
      applyPreset: "应用",
      saveAsPreset: "存为预设",
      preview: "预览",
      done: "关闭",
      unpin: "取下便签",
      delete: "删除",
      deleteConfirmTitle: "删除事件",
      deleteConfirmMsg: "确定要删除此事件吗？此操作无法撤销。"
    },
    styles: {
      clip: "回形针",
      pin: "图钉",
      tape: "胶带",
      spiral: "螺旋本",
      washi: "和纸胶带",
      minimal: "极简",
      torn: "撕纸",
      flower: "花朵",
      leaf: "树叶"
    },
    textures: {
      solid: "纯色",
      lined: "横线",
      grid: "方格",
      dots: "点阵"
    },
    status: {
      todo: "待执行",
      inProgress: "执行中",
      partial: "部分完成",
      done: "执行结束"
    },
    importance: {
      high: "高",
      medium: "中",
      low: "低"
    },
    help: {
      title: "NoteMinder 使用说明",
      sections: {
        general: {
          title: "总体概览",
          items: [
            "本项目由 Gemini 3 Pro Preview 生成，并由 Vibe Coding 完成。",
            "欢迎使用 NoteMinder！这是一款结合了拟物化设计的智能任务管理工具。",
            "书架 (Bookshelf)：您的主工作区背景。包含常用链接书本，提供整洁的桌面环境。",
            "笔记本库 (Notebooks)：核心数据结构。您可以创建多个笔记本（如工作、个人）来分类管理任务。",
            "便签 (Note)：任务的桌面便利贴视图。将笔记本中的任务“固定”到桌面，即可随时查看和编辑。"
          ]
        },
        bookshelf: {
          title: "书架 (Bookshelf)",
          items: [
            "工作区背景。点击侧边栏“书本”图标进入纯净桌面模式。",
            "交互书籍：鼠标悬停会有抽出效果。单击打开网页，双击编辑链接。",
            "填充空位：点击灰色的空白书本即可添加新链接。",
            "书籍管理：您也可以在设置中批量编辑所有书本的标题和网址。"
          ]
        },
        notebooks: {
          title: "笔记本库 (Notebooks)",
          items: [
            "任务分类容器。双击重命名，拖拽排序。",
            "点击“+”新建，悬停点击“X”删除。"
          ]
        },
        notebook: {
          title: "当前列表 (Notebook)",
          items: [
             "核心表格视图。双击单元格编辑，支持AI识别。",
             "高级筛选：点击工具栏的“筛选”按钮，可按日期范围、状态（如“部分完成”）、优先级进行组合过滤。",
             "一键固定/取消：点击“层叠”图标将当前视图所有任务固定到桌面；点击“取消固定”图标（Pin Off）可一键清除桌面便签。",
             "今日待办：点击侧边栏“日历”图标，仅显示今日任务。",
             "状态操作：使用操作列的按钮快速切换状态。新增“部分完成”（橙色饼图）状态。",
             "时间编辑：在编辑模式下，如果列宽不足，日期和时间选择器会自动换行排列，方便操作。"
          ]
        },
        note: {
          title: "桌面便签 (Note)",
          items: [
             "视图模式：'桌面便签'显示所有固定项；'今日便签'仅显示今日固定项。",
             "样式设置：点击设置齿轮，面板会在便签侧边打开。",
             "装饰位置：支持8个方位的装饰（左上、右下等）。",
             "预设系统：在设置中保存常用样式组合，一键应用。",
             "状态显示：便签底部显示当前状态图标（待办、进行中、部分完成、已完成）。"
          ]
        },
        settings: {
          title: "系统设置",
          items: [
             "主题：调整透明度、背景图。",
             "书架桌面：管理书本链接。",
             "便签预设：创建和管理常用的便签外观模板。",
             "自动保存 (Auto-Save)：在“常规”选项卡中设置自动保存间隔。开启后，系统会定时自动下载 XLSX 备份文件到本地下载文件夹。",
             "AI / 大模型：配置您偏好的模型服务商（Gemini, DeepSeek, OpenAI），以及自定义 Prompt。"
          ]
        },
        update: {
          title: "更新日志",
          items: [
            "v4.8.0: 新增“部分完成”状态、一键取消固定、高级筛选栏，优化了编辑时的布局。",
            "v4.6.0: 增加自动保存 (Auto-Save) 设置。",
            "v4.5.0: 增加 LLM 多模型配置，分离日期/时间选择器，笔记本增加状态操作按钮，周工时导出优化。",
            "v4.4.0: 增加 XLSX 批量导入导出功能，完善帮助文档，优化界面细节。",
            "v4.3.0: 增强设置功能，交互式书架，UI 改进。"
          ]
        }
      }
    }
  }
};
